#!/bin/bash
set -x
SDK_BOARD="galileo"
SDK_BRANCH="dylan"

#######################################################################################################################
# Library check

function message_fail_libsh()
{
	    local ZENITY_INSTALLED
        ZENITY_INSTALLED=`dpkg-query -l | grep zenity-common |& awk -F" " '{ print $1 }'`

	    if [ "${ZENITY_INSTALLED}" != "ii" ]
	    then
		    echo "Impossible to connect to internet. Please, double check your Internet connection"
	    else
		    zenity --error --text "Impossible to connect to internet. Please, double check your Internet connection"
	    fi
}

if [ ! -d libsh ]
then
	git clone https://github.com/architech-boards/libsh.git
	[ $? -eq 0 ] || { message_fail_libsh; exit 1; }
fi
cd libsh
git pull
[ $? -eq 0 ] || { message_fail_libsh; exit 1; }
source lib.sh
get_sudo_password ${SUDO_PASSWORD}
cd ..

URL_DOWNLOAD=$(get_url_download)

#######################################################################################################################
# Check maintenance

check_maintenance

###########################################################################################################
# Parameters

YOCTO_DIRECTORY="yocto"
cd ..
ROOT_DIRECTORY=`pwd`
BASEROOT_SDK=${ROOT_DIRECTORY}
NR_CPUS=`grep -c ^processor /proc/cpuinfo`
WGET_TIMEOUT=60


###########################################################################################################
# Get in remote the last version of the package
# S1 url remote 

function get_remote_version {
	wget --timeout=${WGET_TIMEOUT} ${1}/version
	[ $? -eq 0 ] || { internet_error; }
	REMOTE_VERSION=`cat version`
	rm version
	debecho "remote last version of ${1} is ${REMOTE_VERSION}"
}

###########################################################################################################
# Script pre-install

cd $BASEROOT_SDK
wget --timeout=${WGET_TIMEOUT} ${URL_DOWNLOAD}/${SDK_BOARD}/script/${SDK_BRANCH}/pre-script.sh
[ $? -eq 0 ] || { internet_error; }
chmod 777 pre-script.sh
./pre-script.sh
rm pre-script.sh

###########################################################################################################
# Versioning installation if not exist, 1 is the starting version in remote server

[ ! -f conf/versions ] && { debecho "conf/versions created"; mkdir -p ${BASEROOT_SDK}/conf; echo "toolchain:0" > ${BASEROOT_SDK}/conf/versions; echo "sdk:0" >> ${BASEROOT_SDK}/conf/versions; echo "yocto:0" >> ${BASEROOT_SDK}/conf/versions; }

###########################################################################################################
# Yocto installation

cd $BASEROOT_SDK
get_remote_version ${URL_DOWNLOAD}/${SDK_BOARD}/yocto/${SDK_BRANCH}
LOCAL_VERSION=`grep "yocto" conf/versions | awk -F":" '{print $2}'`
debecho "LOCAL_VERSION of yocto is ${LOCAL_VERSION}"
while [ ${LOCAL_VERSION} -lt ${REMOTE_VERSION} ]
do
    ((LOCAL_VERSION++))
    case  ${LOCAL_VERSION}  in
		"1")
            mkdir -p yocto
            cd yocto
            wget --timeout=${WGET_TIMEOUT} ${URL_DOWNLOAD}/${SDK_BOARD}/yocto/${SDK_BRANCH}/${LOCAL_VERSION}/meta-clanton_v1.0.1.tar.gz
            [ $? -eq 0 ] || { cd ..; rm -rf meta-clanton_v1.0.1.tar.gz; internet_error; }

            tar -zxf meta-clanton_v1.0.1.tar.gz
            rm -rf meta-clanton_v1.0.1.tar.gz;

            wget --timeout=${WGET_TIMEOUT} ${URL_DOWNLOAD}/${SDK_BOARD}/yocto/${SDK_BRANCH}/${LOCAL_VERSION}/patches_v1.0.4.tar.gz
            [ $? -eq 0 ] || { cd ..; rm -rf patches_v1.0.4.tar.gz; internet_error; }

            tar -zxf patches_v1.0.4.tar.gz
            rm -rf patches_v1.0.4.tar.gz;

            ./patches_v1.0.4/patch.meta-clanton.sh
            rm -rf patches_v1.0.4
            cd meta-clanton_v1.0.1
            sed -i "s|yocto:$((LOCAL_VERSION-1))|yocto:${LOCAL_VERSION}|g" conf/versions
            cd ${BASEROOT_SDK}
        ;;
    esac
done

###########################################################################################################
# conf/local.conf customization

cd ${BASEROOT_SDK}/yocto/yocto_build
set_cpu_localconf ${NR_CPUS} ./conf

if [ -n "`grep "^PACKAGE_CLASSES" conf/local.conf`" ]
then
    MATCH_LINE=`grep "^PACKAGE_CLASSES" conf/local.conf`
    sed -i "s|^${MATCH_LINE}|PACKAGE_CLASSES ?= \"package_ipk\"|g" conf/local.conf
else
    echo "PACKAGE_CLASSES ?= \"package_ipk\"" >> conf/local.conf
fi

###########################################################################################################
# conf/bblayers.conf customization
#
# None To Do

###########################################################################################################
# Installing cross-toolchain

cd ${ROOT_DIRECTORY}

get_remote_version ${URL_DOWNLOAD}/${SDK_BOARD}/toolchain/${SDK_BRANCH}
LOCAL_VERSION=`grep "toolchain" conf/versions | awk -F":" '{print $2}'`
debecho "LOCAL_VERSION of toolchain is ${LOCAL_VERSION}"
while [ ${LOCAL_VERSION} -lt ${REMOTE_VERSION} ] 
do
		((LOCAL_VERSION++))
		debecho "toolchian install version: ${LOCAL_VERSION}/${REMOTE_VERSION}"
		cd ${ROOT_DIRECTORY}
		rm -rf temp
		mkdir -p temp
		cd temp
		wget --timeout=${WGET_TIMEOUT} ${URL_DOWNLOAD}/${SDK_BOARD}/toolchain/${SDK_BRANCH}/${LOCAL_VERSION}/toolchain.txt
		[ $? -eq 0 ] || { cd ..; rm -rf temp; internet_error; }
		TOOLCHAIN_TARBALL=`cat toolchain.txt | awk -F" " '{print $1}'`
		TOOLCHAIN_MD5=`cat toolchain.txt | awk -F" " '{print $2}'`
		INSTALL_TOOLCHAIN="yes"
		if [ -f ../toolchain/toolchain.txt ]
		then
			diff ../toolchain/toolchain.txt toolchain.txt
			if [ $? -eq 0 ]
			then
				INSTALL_TOOLCHAIN="no"
			fi
		fi

		if [ "${INSTALL_TOOLCHAIN}" == "yes" ]
		then
			wget --timeout=${WGET_TIMEOUT} ${URL_DOWNLOAD}/${SDK_BOARD}/toolchain/${SDK_BRANCH}/${LOCAL_VERSION}/${TOOLCHAIN_TARBALL}.tar.gz
			[ $? -eq 0 ] || { cd ..; rm -rf temp; internet_error; }
			sync
			DOWNLOAD_MD5=`md5sum ${TOOLCHAIN_TARBALL}.tar.gz | awk -F" " '{print $1}'`
			[ "${TOOLCHAIN_MD5}" != "${DOWNLOAD_MD5}" ] && { cd ..; rm -rf temp; internet_error; }
			tar -xzf ${TOOLCHAIN_TARBALL}.tar.gz
			./install.sh
			echo "${TOOLCHAIN_TARBALL} ${TOOLCHAIN_MD5}" > ../toolchain/toolchain.txt
		fi

		cd ..
		rm -rf temp/
		sed -i "s|toolchain:$((LOCAL_VERSION-1))|toolchain:${LOCAL_VERSION}|g" conf/versions
done

###########################################################################################################
# Installing sdk enviroment

DATE_BACKUP=`date +%d%m`

# restore backup if something goes wrong
undo_backup()
{
	if [ -f ${1}.$DATE_BACKUP.tgz ]; then 
		rm -rf ${1}
		tar -zxf ${1}.$DATE_BACKUP.tgz
	fi
}

do_backup()
{
	if [ -d ${1} ]; then 
		rm ${1}.*.tgz
		tar -zcf ${1}.$DATE_BACKUP.tgz ${1}
		rm -rf ${1}
	fi
}

install_file()
{
	echo Install $CMD
	URL=`echo $LINE | awk -F"@" '{print $2}'`
	FILE=$CMD.tgz
	do_backup $CMD
	rm -rf $CMD
	wget --timeout=${WGET_TIMEOUT} ${URL}
	[ $? -eq 0 ] || { rm -f $FILE; undo_backup $CMD; rm conf/sdk.txt; internet_error; }
	mkdir $CMD
	tar -zxf $FILE -C $CMD
	find ${CMD} -type f -exec sed -i "s|@BASEROOT_SDK@|${BASEROOT_SDK}|g" '{}' \;
	[ $? -eq 0 ] || { rm -f $FILE; undo_backup $CMD; rm conf/sdk.txt; internet_error; }
	rm -f $FILE
}

cd $ROOT_DIRECTORY

killall eclipse

get_remote_version ${URL_DOWNLOAD}/${SDK_BOARD}/sdk/${SDK_BRANCH}
LOCAL_VERSION=`grep "sdk" conf/versions | awk -F":" '{print $2}'`
debecho "LOCAL_VERSION of sdk is ${LOCAL_VERSION}"

while [ ${LOCAL_VERSION} -lt ${REMOTE_VERSION} ] 
do
		((LOCAL_VERSION++))
		debecho "sdk install version: ${LOCAL_VERSION}/${REMOTE_VERSION}"

		# dowload script file to know what to do
		rm -f conf/sdk.txt
		wget --timeout=${WGET_TIMEOUT} -P conf ${URL_DOWNLOAD}/${SDK_BOARD}/sdk/${SDK_BRANCH}/${LOCAL_VERSION}/sdk.txt
		[ $? -eq 0 ] || { rm conf/sdk.txt; internet_error; }
        sed -i "s|#URL_DOWNLOAD#|${URL_DOWNLOAD}|g" conf/sdk.txt

		while read LINE; do

			CMD=`echo "${LINE}" | awk -F"@" '{print $1}'`

			if [ -f conf/sdk.txt.old ] 
			then
				grep "${LINE}" conf/sdk.txt.old
				[ $? -eq 0 ] && { continue; }
			fi

			case  $CMD  in
						# install or upgrade java runtime
						"java")
							echo "JAVA"
							URL=`echo $LINE | awk -F"@" '{print $2}'`
							FILE=`echo $LINE | awk -F"@" '{print $3}'`
							VERSION=`echo $LINE | awk -F"@" '{print $4}'`

							if [ ! -d java/$VERSION ]
							then
								do_backup "java"
								rm -rf java
								wget --timeout=${WGET_TIMEOUT} ${URL}
								[ $? -eq 0 ] || { rm -f $FILE; undo_backup "java"; rm conf/sdk.txt; internet_error; }
								mkdir java
								tar -zxf $FILE -C java
								[ $? -eq 0 ] || { rm -f $FILE; rm -rf java; undo_backup "java"; rm conf/sdk.txt; internet_error; }
								rm -f $FILE
								mv java/$VERSION/* java/
							fi
							;;
						# install
						"eclipse")
							echo Install $CMD
							URL=`echo $LINE | awk -F"@" '{print $2}'`
							FILE=`echo $LINE | awk -F"@" '{print $3}'`
							do_backup "eclipse"
							rm -rf eclipse
							wget --timeout=${WGET_TIMEOUT} ${URL}
							[ $? -eq 0 ] || { rm -f $FILE; undo_backup "eclipse"; rm conf/sdk.txt; internet_error; }
							tar -zxf $FILE
							[ $? -eq 0 ] || { rm -f $FILE; undo_backup "eclipse"; rm conf/sdk.txt; internet_error; }
							rm -f $FILE
							;;
						"plugin")
						# install or upgrade plugin of eclipse
							echo "PLUGIN"
							REPOSITORY=`echo $LINE | awk -F"@" '{print $2}'`
							PLUGIN=`echo $LINE | awk -F"@" '{print $3}'`
							VERSION=`echo $LINE | awk -F"@" '{print $4}'`
							./eclipse/eclipse -vm java/bin -application org.eclipse.equinox.p2.director -noSplash -repository $REPOSITORY -installIUs $PLUGIN/$VERSION
							[ $? -eq 0 ] || { rm conf/sdk.txt; internet_error; }
							;;
						"conf")
						# configure yocto plugin
							echo "CONF"
							PATH_CONF=`echo $LINE | awk -F"@" '{print $2}'`
							FILE=`echo $LINE | awk -F"@" '{print $3}'`
							wget --timeout=${WGET_TIMEOUT} ${URL_DOWNLOAD}/${SDK_BOARD}/sdk/${SDK_BRANCH}/${LOCAL_VERSION}/$FILE
							[ $? -eq 0 ] || { rm conf/sdk.txt; internet_error; }
							sed -i "s|@BASEROOT_SDK@|${BASEROOT_SDK}|g" $FILE
							mkdir -p $PATH_CONF > /dev/null 2>&1
							mv $FILE $PATH_CONF
							;;
						"build_workspace")
						# build or rebuild the workspace
							./eclipse/eclipse -vm java/bin -nosplash -application org.eclipse.jdt.apt.core.aptBuild -data ${ROOT_DIRECTORY}/workspace/eclipse
							mkdir -p ${ROOT_DIRECTORY}/workspace/qt
							;;
						"cmd")
						# execute a shell command from the script
							echo "CMD"
							EXECMD=`echo "${LINE}" | awk -F"@" '{print $2}'`
							${EXECMD}
							;;        
						*)
							echo "IGNORED: ${LINE}"
				  esac
		done < conf/sdk.txt

		[ -f conf/sdk.txt ] && { mv conf/sdk.txt conf/sdk.txt.old; }
		sed -i "s|sdk:$((LOCAL_VERSION-1))|sdk:${LOCAL_VERSION}|g" conf/versions
done

###########################################################################################################
# Installing documentation

cd $BASEROOT_SDK
wget --timeout=${WGET_TIMEOUT} ${URL_DOWNLOAD}/${SDK_BOARD}/sdk/${SDK_BRANCH}/getdoc.txt
[ $? -eq 0 ] || { rm -f getdoc.txt; internet_error; }
URL=`grep "@" getdoc.txt | awk -F"@" '{print $1}'`
FILE=`grep "@" getdoc.txt | awk -F"@" '{print $2}'`
rm getdoc.txt
mkdir -p docs;
if [ "${URL}" != "" -a "${FILE}" != "" ]
then
    wget --timeout=${WGET_TIMEOUT} ${URL}
    [ $? -eq 0 ] || { rm -f $FILE; internet_error; }
    unzip -o $FILE -d docs
    rm -f $FILE
else
    echo "No documentation avaiable"
fi

###########################################################################################################
# Script post-install

cd $BASEROOT_SDK
wget --timeout=${WGET_TIMEOUT} ${URL_DOWNLOAD}/${SDK_BOARD}/script/${SDK_BRANCH}/post-script.sh
[ $? -eq 0 ] || { internet_error; }
chmod 777 post-script.sh
./post-script.sh
rm post-script.sh

exit 0

